### ISSUE TITLE
Spotify Lite support

### ISSUE THREAD

**Issue by Nabokov86** [aghontpi/ad-silence#12]
https://play.google.com/store/apps/details?id=com.spotify.lite

**Comment by aghontpi** [comment]
Good suggestion, will add it !

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [block Spotify lite ads](https://trello.com/c/0kMXxm4W/35-block-spotify-lite-ads)

**Comment by aghontpi** [comment]
Hi!, there is a test build [here](https://github.com/aghontpi/ad-silence/pull/13#issuecomment-1004431223), if you want to test it/try it early.

 If you decide to test it, do give feedback on whether it works or not.

**Comment by Nabokov86** [comment]
@aghontpi Works great for me! 

Thank you for such a quick update!
