### ISSUE TITLE
App was temporarily removed from google playstore due to "policy violation"

### ISSUE THREAD

**Issue by aghontpi** [aghontpi/ad-silence#19]
The reasoning mentioned was that the "app Icon" was in violation of the terms. I'm contacting `policy support team` regarding this issue.

I'll update this thread on updates.

**Solution**

You can still use one of the following links to get the official apks

 - https://f-droid.org/packages/bluepie.ad_silence/ 
 - https://github.com/aghontpi/ad-silence/releases

### update 1

App was reinstated after Changing the Icon and Submitting for review.

**Comment by aghontpi** [comment]
Update:

I've made an updated build with new App Icon and submitted it for review, they resolved it. Its available on PlayStore now!.

**Comment by ExplodieSway** [comment]
I wonder what the problem was with the icon. Do they don't allow ad-blockers on there?

**Comment by aghontpi** [comment]
Yes, they allow ad-blockers.. I even sent them a few examples stating the same, but their response was bleak.

```Please note that any perceived compliance or non-compliance of other developers’ apps does not have any bearing on the compliance of your own apps. If you want to report an app that you believe is a violation of our developer terms, please flag it as inappropriate on Google Play or submit a report through our contact form.```

below is the full response
![938748318273848](https://user-images.githubusercontent.com/18617846/151644186-eccc82e3-44bd-4d46-8bdf-563e242c1311.png)

**Comment by aghontpi** [comment]
I was furious at that point and sent the following response, 

```
What in the world? you expect me to accept this as an answer? 

How is the icon violating terms? I see no wrong with the old app Icon, that was my main concern for contact support, that is not even addressed in your response.

Apps with huge audiences should not be compared to?...what?....this is absurd.
```

**Comment by ExplodieSway** [comment]
We can only wait for their response and hope it was a mistake from their side, although unlikely. But I'm pretty sure it's a false positive they got.

**Comment by ExplodieSway** [comment]
Any updates?

**Comment by aghontpi** [comment]
I got a reply, but I suspect it was from a bot. 

```
Hi <name-removed>,

Thanks for your reply.

I see your app, Ad-silence - OpenSource (bluepie.ad_silence), was resubmitted earlier and has been approved.

Your app now is live on Google Play via this link: https://play.google.com/store/apps/details?id=bluepie.ad_silence

Thanks for working with us to fix the policy issues and for your support of Google Play.

Please let me know if I can help with anything else.
```

None of my questions were addressed...Im not gonna pursue this further. 

I do sympathise with them because they have to process a lot of requests... but this is just pain (╯°□°）╯︵ ┻━┻

**Comment by ExplodieSway** [comment]
Looks like a bot trying to be personal or a person who suspiciously replies like a bot... morever, we might as well close this issue since the app is now live on Play Store again.

Google's a pain sometimes.

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix for playstore](https://trello.com/c/aaZZZGw5/41-fix-for-playstore)

**Comment by aghontpi** [comment]
I believe the later is true, 

closing this issue, since the updated icon seems to work and no violations until now.
