### ISSUE TITLE
Doesn't unmute on Android 5.x using Spotify Lite

### ISSUE THREAD

**Issue by wackydroid** [aghontpi/ad-silence#20]
I've tested on android 5.0.1 (x2), 5.0.2 and the ads are muted, but when the next song comes on it is still muted. I'm not able to manually unmute w/o closing the ad-silence app.

I've tested on Android 6.0 and 7.1 and there are no issues with muting and unmuting.

**Comment by aghontpi** [comment]
Hi @wackydroid, thanks for the bug report!

Have you tested `Spotify` on the same 5.x.x device?. Just today, I encountered a weird behaviour  where unmuting did not work for **`Spotify Stations`** in #21. It worked fine when I tested it on `Accuradio & Spotify`.  This may help to verify if this is a app specific issue.

this happened on `android 11` and haven't tested on other android versions yet.

**Comment by wackydroid** [comment]
Same result with Spotify. Does not unmute.

**Comment by aghontpi** [comment]
Thank you, I identified it and made a patch

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [android 5.x unmute does not work](https://trello.com/c/P1UCtwZB/40-android-5x-unmute-does-not-work)

**Comment by wackydroid** [comment]
Fix verified in 0.5.2.
