### ISSUE TITLE
Possbile Spotify Issue

### ISSUE THREAD

**Issue by monsterPANINI** [aghontpi/ad-silence#23]
I really like listen to spotify and the ads are really annoying i hope that you guys can fix it, have a great day 
:)

**Comment by aghontpi** [comment]
Hi @monsterPANINI, can you share the following details..

what is your android version?

device vendor?

app version used?

spotify version used?

device language?

is Spotify enabled in app selection?

can you see `Ad-silence` notification?

If notification is showing what does the notification text say when ad is playing?

**Comment by aghontpi** [comment]
closing this due to inadequate info, @monsterPANINI reopen this with the requested information.
