### ISSUE TITLE
support for antennapod

### ISSUE THREAD

**Issue by Kreuger** [aghontpi/ad-silence#25]
Hey I was just wondering if you could get this to work with AntennaPod. Im guessing since the ads are embedded into the podcasts and wouldnt change in the notification, it isnt possible?

**Comment by aghontpi** [comment]
Hello,

Yea, If the ads are embedded into the podcasts with no notification change, it is not possible.

**Comment by Kreuger** [comment]
Thanks anyways!

**Comment by aghontpi** [comment]
:+1: 

closing this issue. reopen/ create new issue if you need further assistance.
