### ISSUE TITLE
Request to add steaming app

### ISSUE THREAD

**Issue by deblood3** [aghontpi/ad-silence#28]
I am thrilled with the efficacy of your app in muting add in the current list of streaming apps

I am making a request if you can add
Livexlive

**Comment by aghontpi** [comment]
Hello @deblood3, can you confirm if this is the app link "play.google.com/store/apps/details?id=com.slacker.radio"

looks like this app is a music video app, I can mute the ads in this but will this be useful?

**Comment by aghontpi** [comment]
Is this the only `ad type` present in the app?


![LiveXLive](https://user-images.githubusercontent.com/18617846/153259328-08035b77-5d55-4694-a0ce-35562014313a.jpg)

**Comment by deblood3** [comment]
Thanks for your inquiry. Yes, it's audio and video streaming app. They just changed the name to Liveone. Sorry l couldn't get you the initial link as the "share" wasn't available when l.posted the request but link is 👇 
https://play.google.com/store/apps/details?id=com.slacker.radio

**Comment by aghontpi** [comment]
Looks like also imposed geo restrictions. I'm unable install this on my device now.

![29342342349238423](https://user-images.githubusercontent.com/18617846/153916312-e1534cbe-b207-455b-8797-b2dd577deaa7.png)

If this can be used as a music app with background listening. I can surely add it 👍

**Comment by deblood3** [comment]
Aghontpi, thanks for looking at it, but not a problem if your are limited by geo location restrictions

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add support for "liveOne"](https://trello.com/c/OcEgsAtc/43-add-support-for-liveone)

**Comment by aghontpi** [comment]
Sorry It took this much time.

Its region blocked but thats fine. I can use workarounds..to make the app work. 

reopening this issue.

**Comment by deblood3** [comment]
Yes, that is the requested app, it's a music streaming app, but they sometimes have video ads, that asked the listener to watch and get 30mins uninterrupted streaming music. 

If you can mute the ads that will be a plus but if muting the ads will cause issues then you can ignore it.  

But thanks for the efforts to address my request.
