### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Saanjh95** [aghontpi/ad-silence#37]

**Comment by famewolf** [comment]
Device?  Android Version?  Rom?   Logcat from when error occurred?

**Comment by aghontpi** [comment]
@Saanjh95 Kindly provide the info requested.

also describe the error, ex: is it not launching, crashing or doesn't work on a particular app etc...

**Comment by aghontpi** [comment]
@Saanjh95 open this issue when you have the requested details...until then closing this issue due to lack of info.

**Comment by Saanjh95** [comment]
Android version
