### ISSUE TITLE
Support for Youtube Music?

### ISSUE THREAD

**Issue by XamDR** [aghontpi/ad-silence#39]
Hello. After watching a video on YouTube I discovered your app xd and I was wondering if you plan to support YouTube Music (the app version).  Have you considered it?

**Comment by aghontpi** [comment]
Hello, yes I would add it but it has limitations to free accounts, so it is impossible to detect whether music/ad is playing.

Used the [official app](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music)

- without subscription
  - it pauses the playback when you minimise the app or lock the screen.
  - **does not post notification about current playback (to add support for `YouTube music`, this is necessary)**

**Comment by famewolf** [comment]
Have you tested using alternative apps such as Newpipe from f-droid.org?  Actually many of those alternatives already block the ads come to think of it although i have not yet found one dedicated to just pulling the audio.  Newpipe is a full youtube app replacement.

**Comment by XamDR** [comment]
> Hello, yes I would add it but it has limitations to free accounts, so it is impossible to detect whether music/ad is playing.
> 
> Used the [official app](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music)
> 
> * without subscription
>   
>   * it pauses the playback when you minimise the app or lock the screen.
>   * **does not post notification about current playback (to add support for `YouTube music`, this is necessary)**

Ah yes I didn't think of those limitations for free accounts. Seems it's a dead end then.

**Comment by aghontpi** [comment]
@famewolf is right, you could try [NewPipe](https://github.com/TeamNewPipe/NewPipe/releases).

closing... feel free to open this issue if there is an update.
