### ISSUE TITLE
Plsss add youtube music

### ISSUE THREAD

**Issue by ghost** [aghontpi/ad-silence#45]

**Comment by Jordanboonemurray** [comment]
[https://audiomack.com/jordanryanmurray/song/mud-to-quick-sand](https://audiomack.com/jordanryanmurray/song/mud-to-quick-sand) @aghontpi @aghontpi @RavenIshigami @RavenIshigami

**Comment by aghontpi** [comment]
Hi @Jordanboonemurray.

support for YouTube music has already been discussed here https://github.com/aghontpi/ad-silence/issues/39
