### ISSUE TITLE
Ad blocking in Spotify doesn't work

### ISSUE THREAD

**Issue by erawhctim** [aghontpi/ad-silence#5]
Info: 
- Pixel 6
- Android 12 (Build #SD1A.210817.027, if that matters)
- Spotify v8.6.82.1113

Tried playing a podcast on Spotify, waiting for Ads, and nothing happened. The ads play, I see "Advertisement" in the notification title, and I see the Ad Silence persistent notification (so the app was running). I had granted permission before running Spotify, and seemed to complete all the steps required to configure Ad Silence 🤔

I can try and debug locally to get some more info in logcat - are there specific log tags/messages I can search for or filter on?

**Comment by aghontpi** [comment]
I haven't tested podcasts in spotify, I'll check them out.

you can check this line below in logs https://github.com/aghontpi/ad-silence/blob/ec5df7e6960a5f62b7088f36687b713a861d9cca/app/src/main/java/bluepie/ad_silence/NotificationParser.kt#L91-L96

**Comment by aghontpi** [comment]
okey, so I tried running podcasts on a account with no subscription, I did not get ads in them to test. (not including the ads baked into the episode itself by the creator)

can you link the podcasts?, if you dont want to share it publicly, send it to me directly.

**Comment by Aldormb** [comment]
Tbm fiz todos os passos, a notificação do app diz q ele está aberto,porém os anúncios continuam

**Comment by erawhctim** [comment]
@aghontpi I just pulled up the latest episode of Joe Rogan's podcast to test. Ads appear after a little while, though (not immediate), and the exact point in time where they trigger the ad(s) seems to vary slightly between episodes.

The ad appears as a different "track" and has its own standalone notification (which seems to be what your app needs to detect with). I can try running locally and searching in the logs; I'll see if I can copy them and post here.

**Comment by aghontpi** [comment]
Thanks!, I found it, this is a great find!!
 
![bug spotify bug](https://user-images.githubusercontent.com/18617846/145180288-04a09a6d-476e-45d8-9ba3-a6ecb23333e0.png)

**Comment by aghontpi** [comment]
the build below should cover this.

(rename .zip to .apk, limitations in github comments)
[app-release.zip](https://github.com/aghontpi/ad-silence/files/7680973/app-release.zip)

testing for a day before closing this.

**Comment by ouzowtf** [comment]
Just installed version 0.9.1 to test this with Spotify and I got ads playing while playing an auto-generated playlist ("Your mixtape")

**Comment by aghontpi** [comment]
yea 0.2.1. @ouzowtf  I tried mixtape, the ad shows up but the app detects and silences it. I'll keep on testing it in the upcoming days.., meanwhile I'm keeping this issue closed (since this is related to podcasts), you can open a new issue.

**Comment by citizenserious** [comment]
I use Spotify premium, but I still have advertisement while listening to podcasts. Unfortunately ad silencing doesn't work. Maybe it is not working because the adds are labeled as "Spotify" instead as advertisement?

**Comment by aghontpi** [comment]
@citizenserious maybe the `ads` are baked in the original podcast file/audio by the creator.

**Comment by citizenserious** [comment]
@aghontpi, no thats not the case, it is advertisment for other podcasts The screenshot that I shared shows the advertised show, not the one that I listen to.

**Comment by aghontpi** [comment]
@citizenserious this has to be added to spotify "detections".

created new issue here #59

**Comment by aghontpi** [comment]
@citizenserious there is no mention of "ad" in the song title or notification. how do we block this..

The artist name is `Spotify` maybe that can be used 🤔

**Comment by citizenserious** [comment]
@aghontpi Exactly I think that is the problem here. We could try it with adding the name `Spotify` but I do not know if there are any side affects like false blocking or worse. I would test it for a while if you like to provide a test version. (:

**Comment by aghontpi** [comment]
@citizenserious, yea true.

I'll refactor/ do the changes and tag you in #63 with the build

**Comment by citizenserious** [comment]
@aghontpi you are the best! Thank you very much for your work.

**Comment by citizenserious** [comment]
@aghontpi 

I found several Sponsors which are not silenced yet:

![Screenshot_20230524-142611_Spotify](https://github.com/aghontpi/ad-silence/assets/62773866/cc891820-35a2-42d3-92d6-5781a635de7d)
![Screenshot_20230524-142748_OctoDroid](https://github.com/aghontpi/ad-silence/assets/62773866/96d9770d-b702-46d0-9ab3-d3a8ed132901)
![Screenshot_20230524-142658_Spotify](https://github.com/aghontpi/ad-silence/assets/62773866/3282edc3-8b0a-4c80-b952-53
![Screenshot_20230524-142803_OctoDroid](https://github.com/aghontpi/ad-silence/assets/62773866/d45e39fd-777a-4d7b-aa0d-41b1cc78e47d)
a93261f021)
![Screenshot_20230524-142626_Spotify](https://github.com/aghontpi/ad-silence/assets/62773866/d636c8be-9bd9-43f1-95af-a40fb75dc064)

If you could show me how you added it last time I am willing to try it myself, but consider, that I never partisipaded at a project on github or any comparable platform.
Maybe I could start with that, trying to participate at this awesome project (:
