### ISSUE TITLE
Spotify ad notifications blank

### ISSUE THREAD

**Issue by wjhrdy** [aghontpi/ad-silence#58]
seems like spotify might have blanked out its advertisement notifications.
using https://f-droid.org/en/packages/de.jl.notificationlog/
I looked at the spotify notifications when ads came on and they were blank.
they are also not being muted but I think this is why.
![signal-2022-06-30-141821](https://user-images.githubusercontent.com/1795778/176749866-7386e83e-fa67-4c94-8166-fb54d31b76db.jpeg)

**Comment by aghontpi** [comment]
🤔 does this behavior occur only for `ads`. 

 next time this occurs kindly take a screenshot of the `Spotify` notification,

I'll test this behaviour from my end aswell.

**Comment by wjhrdy** [comment]
Heavyweight Podcast is a great one to test with because all the numbered episodes have an ad in the first few minutes.

**Comment by aghontpi** [comment]
> Some use the advertisement keyword some dont.

This is a problem.



In the notification logs, the song title is blank, but in screenshot, the title and artist names are present 🤔

**Comment by aghontpi** [comment]
#64 fixes, this.

@wjhrdy try out the new build https://github.com/aghontpi/ad-silence/releases
