### ISSUE TITLE
Co-maintainers

### ISSUE THREAD

**Issue by aghontpi** [aghontpi/ad-silence#85]
I was unavailable for a while because of personal reasons and a lot of work & improvements are in [backlog](https://trello.com/b/8XJDVbdo/ad-silence-android) now.
It would be good if there are multiple people to oversee this project, if incase anyone is unavailable others can take over and do sanity checks and do hot fixes.

what do you think, would you be interested?

@famewolf
@citizenserious

**Comment by citizenserious** [comment]
I would if I could but unfortunately I lack the skills to help. I'm not a programmer.

**Comment by famewolf** [comment]
Although I'm a retired mainframe programmer I retired for health reasons
and can't really take on anything like this (on top of not doing any pc
programming other than simple bash scripts).  Is there anyone that has
submitted code patches?  They'd be who I might start with.  Sorry.

**Comment by aghontpi** [comment]
@famewolf I understand. thanks for considering my request.

> retired mainframe programmer
that is awesome tbh, hoping one day I could also say something like this 😃.

Do you have a blog where you share your experience/challenges?

**Comment by aghontpi** [comment]
@citizenserious thanks for considering my request, it is fine, no problem.

you can pickup the skills, programming is not that hard 😄

**Comment by famewolf** [comment]
Almost the opposite really. I participate in some forums(deal forums,
finance forums)  but have almost no social footprint.   When I was younger
I  had webpages but went for a more private approach.   I do participate in
open source projects as I can....most bug reports and testing.   I have
enjoyed your app when listening to apps other than plexamp which mainly is
playing my own music collection from a plex server.   I regret I am not in
a position to help more.

**Comment by citizenserious** [comment]
> @citizenserious thanks for considering my request, it is fine, no problem.
> 
> you can pickup the skills, programming is not that hard 😄

I have just started to learn on [freecodecamp ](https://www.freecodecamp.org)in my free time a few weeks ago. So hopefully I can add to projects like this someday (:

**Comment by aghontpi** [comment]
@citizenserious awesome!
