### ISSUE TITLE
[Feature Request] Please add support for SoundCloud 

### ISSUE THREAD

**Issue by Xt3ns1s** [aghontpi/ad-silence#94]

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add soundcloud support](https://trello.com/c/YZGQvj3i/78-add-soundcloud-support)

**Comment by aghontpi** [comment]
@Xt3ns1s thanks for making the request,

Soundcloud has been added and will be part of the next release/build. please follow the next release.

but if you want to use the dev build before the release, kindly follow the steps, 

- uninstall the existing ad-silence app.
- download the attached zip file and rename it to .apk (GitHub comments restrictions), then install it. 
[app-debug.zip](https://github.com/aghontpi/ad-silence/files/12851479/app-debug.zip)

**Comment by Xt3ns1s** [comment]
Thank you! I'll test it and see if it works on my end.

**Comment by aghontpi** [comment]
@Xt3ns1s thanks for making the request, 

Support for `Soundcloud` has been added and will be part of next release/build, please follow the next release.

**info required:**
while the ads are running for soundcloud, are there any other words apart from "Advertisement", like it could be a different word or it could be in a different language. I have only tested & implemented for English lang, please let me know of the same.

**more:** 
 if you want to use the dev build before the release, follow the steps

- uninstall existing ad-silence app
- download the attached .zip and rename to .apk (restrictions to GitHub comments), install it. 

[app-debug.zip](https://github.com/aghontpi/ad-silence/files/12851632/app-debug.zip)

**Comment by aghontpi** [comment]
@Xt3ns1s , I have deleted my previous comment, the build had an issue. please use this instead.. https://github.com/aghontpi/ad-silence/issues/94#issuecomment-1754152478

sry for the confusion
