### ISSUE TITLE
Catalan support

### ISSUE THREAD

**Issue by bluegeekgh** [aghontpi/ad-silence#98]
Please add "Anunci" in Spotify.kt
(Catalan support)
Also some strings are duplicated.
Thanks

**Comment by aghontpi** [comment]
@bluegeekgh thanks for raising this, Spotify.kt should be updated, it was last updated a long time ago, will add the same. 

more: 

- taking the values from decompiled Spotify version: 8.8.76.667
- extracting the labels with this as source [ad_labels.txt](https://github.com/aghontpi/ad-silence/files/12850747/ad_labels.txt)
- 'Anunci' is included.

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update Spotify.kt](https://trello.com/c/gMOVZfCG/80-update-spotifykt)

**Comment by aghontpi** [comment]
added the same, plus added other lang changes and additions based on decompiled files. 

ref: https://github.com/aghontpi/ad-silence/pull/106/files?diff=unified&w=0#diff-c679807db8fdb037191cb222ecc0e5e31c6b3a90c1eefe937346cd9d40dfcb76


@bluegeekgh should see the difference in the next release/build.
